language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '12'
  - '10'
  - '8'
script:
  - npm run test
  - npm run build
after_success:
  - npm run travis-deploy-once "npm run codecov"
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
